"""
VisionTera - Person Detection Model Training (Transfer Learning)
================================================================
Fine-tunes our existing yolo26m.pt detection model on the CrowdHuman dataset
for person detection in high-density crowd scenarios (airports, events, etc.)

Dataset: CrowdHuman from Roboflow (YOLO26 format)
  - 5,078 train images | 3,874 valid images | 1,937 test images
  - Single class: 0 = person (full body bounding boxes)

Usage:
    python research/train_head_detector.py                        # Normal training
    python research/train_head_detector.py --epochs 100           # Custom epochs
    python research/train_head_detector.py --imgsz 960            # High Accuracy resolution
    python research/train_head_detector.py --imgsz 1280           # Ultra Accuracy (needs high VRAM)
    python research/train_head_detector.py --batch 8              # Reduce if GPU OOM
    python research/train_head_detector.py --data path/to/data.yaml  # Custom dataset
"""

from ultralytics import YOLO
import os
import yaml
import argparse
import logging
from pathlib import Path
from datetime import datetime

# ─── Logging Setup ────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - VisionTera.CrowdDetector - %(levelname)s - %(message)s',
)
logger = logging.getLogger("VisionTera.CrowdDetector")

# ─── Project Paths ────────────────────────────────────────────────────────────
PROJECT_ROOT = Path(__file__).parent.parent
RESEARCH_DIR = PROJECT_ROOT / "research"
MODELS_DIR = PROJECT_ROOT / "infrastructure" / "models"

# Use the merged dataset if available, otherwise fallback to standard crowdhuman
MERGED_DATASET_DIR = PROJECT_ROOT / "datasets" / "merged_visiontera"
if MERGED_DATASET_DIR.exists():
    DATASET_DIR = MERGED_DATASET_DIR
else:
    DATASET_DIR = RESEARCH_DIR / "crowdhuman"

# Base detection model - our production yolo26m (NOT nano, NOT classification)
BASE_MODEL_PATH = MODELS_DIR / "yolo26m.pt"


def get_latest_detection_model() -> Path:
    """
    Find the production detection model, falling back to auto-download.
    Note: Only detection models (not classification) can be used as base.
    """
    if BASE_MODEL_PATH.exists():
        logger.info(f"✅ Using production detection model: {BASE_MODEL_PATH}")
        return BASE_MODEL_PATH

    # Fallback: download yolo26m.pt from ultralytics
    logger.warning("⚠️  yolo26m.pt not found locally. YOLO will auto-download it.")
    return Path("yolo26m.pt")


def validate_and_get_dataset_yaml(dataset_path: Path = None) -> str:
    """
    Validate the CrowdHuman dataset and return the path to data.yaml.
    
    Expected Roboflow YOLOv11 dataset structure:
        crowdhuman/
        ├── data.yaml            # Dataset config (auto-generated by Roboflow)
        ├── train/
        │   ├── images/          # Training images (.jpg)
        │   └── labels/          # YOLO format labels (.txt)
        ├── valid/
        │   ├── images/          # Validation images (.jpg)
        │   └── labels/          # YOLO format labels (.txt)
        └── test/
            ├── images/          # Test images (.jpg)
            └── labels/          # YOLO format labels (.txt)
    
    Label format (YOLO): <class_id> <x_center> <y_center> <width> <height>
        class 0 = person
    """
    dataset_path = dataset_path or DATASET_DIR
    roboflow_yaml = dataset_path / "data.yaml"

    # ── Check if Roboflow data.yaml exists ──
    if not roboflow_yaml.exists():
        logger.error(f"""
╔══════════════════════════════════════════════════════════════════╗
║  ⚠️  DATASET NOT FOUND                                          ║
║                                                                  ║
║  Expected dataset at: {str(dataset_path):<40s} ║
║                                                                  ║
║  Download CrowdHuman (YOLOv11 format) from Roboflow:             ║
║    1. Visit: https://universe.roboflow.com/search?q=crowdhuman   ║
║    2. Select "YOLO26" format                                    ║
║    3. Download and extract to: research/crowdhuman/              ║
╚══════════════════════════════════════════════════════════════════╝
        """)
        raise FileNotFoundError(f"Dataset config not found: {roboflow_yaml}")

    # ── Read and fix paths in data.yaml ──
    # Roboflow uses relative paths (../train/images) which can break
    # depending on CWD. We'll create a fixed version with absolute paths.
    with open(roboflow_yaml, 'r') as f:
        data_config = yaml.safe_load(f)

    logger.info(f"📄 Found Roboflow data.yaml with {data_config.get('nc', '?')} classes: {data_config.get('names', [])}")

    # Create a training-ready YAML with absolute paths
    fixed_yaml_path = RESEARCH_DIR / "crowdhuman_train.yaml"
    fixed_config = {
        'path': str(dataset_path.absolute()),
        'train': 'train/images',
        'val': 'valid/images',
        'test': 'test/images',
        'nc': data_config.get('nc', 1),
        'names': data_config.get('names', ['person']),
    }

    with open(fixed_yaml_path, 'w') as f:
        yaml.dump(fixed_config, f, default_flow_style=False)

    logger.info(f"📄 Training config saved: {fixed_yaml_path}")

    # ── Validate dataset contents ──
    train_images = dataset_path / "train" / "images"
    train_labels = dataset_path / "train" / "labels"
    valid_images = dataset_path / "valid" / "images"
    valid_labels = dataset_path / "valid" / "labels"
    test_images = dataset_path / "test" / "images"

    splits = {
        "Train": (train_images, train_labels),
        "Valid": (valid_images, valid_labels),
        "Test":  (test_images, None),
    }

    for split_name, (img_dir, lbl_dir) in splits.items():
        if img_dir.exists():
            img_count = len(list(img_dir.glob("*.jpg"))) + len(list(img_dir.glob("*.png")))
            lbl_count = len(list(lbl_dir.glob("*.txt"))) if lbl_dir and lbl_dir.exists() else 0
            logger.info(f"   📊 {split_name}: {img_count} images, {lbl_count} labels")
        else:
            logger.warning(f"   ⚠️  {split_name} split not found at {img_dir}")

    return str(fixed_yaml_path)


def train_crowd_model(
    data_yaml: str = None,
    epochs: int = 100,
    imgsz: int = 960,
    batch: int = 16,
    freeze: int = 0,
    patience: int = 50,
    resume: bool = False,
):
    """
    Train person detection model via transfer learning from yolo26m.pt.
    Optimized for high-density crowd scenarios.
    
    Strategy for high-crowd areas (VisionTera Ultra-Accuracy):
    - imgsz=960: Higher resolution to detect small/distant heads & bodies
    - freeze=0: Unfreeze all layers to specialize for our 47k merged images
    - multi_scale=True: Train on various resolutions for scale robustness
    - copy_paste=0.1: Better handling of heavy occlusion (from reports)
    - label_smoothing=0.1: Better generalization (prevent overconfidence)
    """
    # Generate version tag
    version_tag = datetime.now().strftime("crowd_v_%Y%m%d_%H%M%S")
    
    # Get base model
    base_model = get_latest_detection_model()
    logger.info(f"🏗️  Base model: {base_model}")
    logger.info(f"🎯 Task: Person detection for high-crowd areas")
    logger.info(f"📦 Version: {version_tag}")

    # Validate dataset and get config
    if data_yaml is None:
        data_yaml = validate_and_get_dataset_yaml()
    
    # Load the base detection model
    model = YOLO(str(base_model))

    # ─── Training Configuration (Crowd-Optimized) ─────────────────────────────
    try:
        results = model.train(
            data=data_yaml,
            epochs=epochs,
            imgsz=imgsz,
            batch=batch,
            patience=patience,
            freeze=freeze,              # Freeze backbone - retain pre-trained features
            
            # ── Save & Project ──
            project=str(MODELS_DIR),
            name=version_tag,
            exist_ok=False,
            
            # ── Optimizer ──
            optimizer='AdamW',
            lr0=0.001,
            lrf=0.01,
            weight_decay=0.001,
            warmup_epochs=3,
            
            # ── Crowd-Specific Augmentation ──
            mosaic=1.0,                 # Enable mosaic - creates dense crowd simulations
            mixup=0.15,                 # Blend images for better crowd generalization  
            scale=0.5,                  # Random scaling - detect people at various distances
            copy_paste=0.1,             # Occlusion simulation for crowded scenes
            erasing=0.4,                # Robustness to partial occlusion
            multi_scale=True,           # Train at ±50% imgsz for distance robustness
            degrees=10.0,               # Slight rotation augmentation
            translate=0.1,
            fliplr=0.5,
            flipud=0.0,                 # No vertical flip (people don't appear upside down)
            hsv_h=0.015,
            hsv_s=0.7,
            hsv_v=0.4,
            label_smoothing=0.1,        # Prevents overconfidence, aids generalization
            
            # ── Detection Tuning ──
            iou=0.5,                   # Lower IoU for crowded NMS (people overlap more)
            conf=0.001,                # Low training conf to learn difficult detections
            
            # ── Performance ──
            amp=True,                  # Mixed precision for faster training
            workers=4,
            seed=42,
            deterministic=True,
            verbose=True,
            plots=True,
            
            # ── Resume ──
            resume=resume,
        )
        
        logger.info("=" * 60)
        logger.info("✅ CROWD DETECTION TRAINING COMPLETE!")
        logger.info(f"💾 Model saved to: {results.save_dir}")
        logger.info(f"📊 Best model: {results.save_dir}/weights/best.pt")
        logger.info("=" * 60)
        
        # Copy best model as best_model.pt (matching our convention)
        import shutil
        best_weights = Path(results.save_dir) / "weights" / "best.pt"
        best_copy = Path(results.save_dir) / "best_model.pt"
        if best_weights.exists():
            shutil.copy2(best_weights, best_copy)
            logger.info(f"📋 Copied best weights to: {best_copy}")
        
        # Log next steps
        logger.info("")
        logger.info("🔄 NEXT STEPS:")
        logger.info(f"   1. Test: python -c \"from ultralytics import YOLO; m=YOLO('{best_copy}'); m.predict('test_image.jpg')\"")
        logger.info(f"   2. Deploy: Copy {best_copy} to infrastructure/models/yolo26m.pt")
        logger.info(f"   3. Or update AppConfig.MODEL_PATH to point to the new model")
        
        return results
        
    except Exception as e:
        logger.error(f"❌ Training failed: {e}")
        logger.error(f"""
╔══════════════════════════════════════════════════════════════════╗
║  TROUBLESHOOTING                                                 ║
║                                                                  ║
║  1. Dataset missing?                                             ║
║     → Download CrowdHuman from Roboflow (YOLOv11 format)        ║
║     → Extract to: research/crowdhuman/                           ║
║                                                                  ║
║  2. GPU out of memory?                                           ║
║     → Reduce batch size: --batch 8 (or even --batch 4)          ║
║     → Reduce image size: --imgsz 480                             ║
║                                                                  ║
║  3. CUDA not available?                                          ║
║     → Training will fall back to CPU (much slower)               ║
║     → Install CUDA: pip install torch torchvision --index-url     ║
║       https://download.pytorch.org/whl/cu121                     ║
║                                                                  ║
║  4. Labels mismatch?                                             ║
║     → Verify labels exist in train/labels/ and valid/labels/     ║
║     → Each .txt should have: <class> <x> <y> <w> <h>            ║
╚══════════════════════════════════════════════════════════════════╝
        """)
        raise


def parse_args():
    parser = argparse.ArgumentParser(
        description="VisionTera - Crowd Person Detection (Transfer Learning from yolo26m.pt)"
    )
    parser.add_argument('--data', type=str, default=None,
                        help='Path to dataset YAML (auto-detected from research/crowdhuman/ if not provided)')
    parser.add_argument('--epochs', type=int, default=100,
                        help='Number of training epochs (default: 100)')
    parser.add_argument('--imgsz', type=int, default=960,
                        help='Image size for training. Use 1280 for ultra accuracy (default: 960)')
    parser.add_argument('--batch', type=int, default=16,
                        help='Batch size. Reduce to 8 or 4 if GPU OOM (default: 16)')
    parser.add_argument('--freeze', type=int, default=0,
                        help='Number of backbone layers to freeze (default: 0 for large datasets)')
    parser.add_argument('--patience', type=int, default=50,
                        help='Early stopping patience (default: 50)')
    parser.add_argument('--resume', action='store_true',
                        help='Resume training from last checkpoint')
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    
    logger.info("🚀 VisionTera Crowd Person Detection - Transfer Learning")
    logger.info(f"   Base: yolo26m.pt (production detection model)")
    logger.info(f"   Dataset: CrowdHuman (Roboflow YOLO26 format)")
    logger.info(f"   Target: Person detection optimized for high-crowd areas")
    logger.info(f"   Epochs: {args.epochs} | ImgSize: {args.imgsz} | Batch: {args.batch}")
    logger.info(f"   Freeze: {args.freeze} layers | Patience: {args.patience}")
    
    train_crowd_model(
        data_yaml=args.data,
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        freeze=args.freeze,
        patience=args.patience,
        resume=args.resume,
    )
