tracker_type: botsort
track_high_thresh: 0.35
track_low_thresh: 0.12
new_track_thresh: 0.35
track_buffer: 48
match_thresh: 0.86
fuse_score: true
gmc_method: sparseOptFlow
proximity_thresh: 0.55
appearance_thresh: 0.82
with_reid: false
model: auto
